### ISSUE TITLE
Modifying the order of page title

### ISSUE THREAD

**Issue by yuma-m** [lxndrblz/anatole#128]
Hi there, thank you for the great theme. I use this for my personal website.

**Is your feature request related to a problem? Please describe.**
It can be a matter of preference, the title of a web page is more likely to be `page title | site name` instead of `site name | page title`.

**Describe the solution you'd like**
The current page title is `author | page title`, but could you consider swapping the order or having an option to change this?

https://github.com/lxndrblz/anatole/blob/6f804985e4e301afc26e9d4cf26b8f3030d8887a/layouts/partials/head.html#L2

**Comment by lxndrblz** [comment]
@yuma-m  Glad you like the theme and thanks for reaching out! The reason why I chose this order originally is because the length of the text until the pipe symbol would be consistent on all pages. I understand that you might want to change this. In this case I would recommend forking the theme and applying the changes to your fork.
