### ISSUE TITLE
Tag “C#” page show 404

### ISSUE THREAD

**Issue by GhostBasenji** [lxndrblz/anatole#163]
When I click on the C# tag, page 404 appears. How did I figure it out that the " # " symbol is specific. How is this resolved?

**Comment by lxndrblz** [comment]
Thanks for bringing this up. I'll need to investigate this and report back!

**Comment by lxndrblz** [comment]
@GhostBasenji I was doing some digging and it seems like certain characters don't work well with Hugo/YAML and it's unfortunately not just a limitation of this theme. The problem is that certain characters are reserved according to the [RFC Standard](https://tools.ietf.org/html/rfc3986)

https://discourse.gohugo.io/t/sanitizing-category-names/11087
https://github.com/gohugoio/hugo/issues/4519
https://discourse.gohugo.io/search?q=special%20characters%20in%20url

I was wondering did C# work you before in another theme?

**Comment by GhostBasenji** [comment]
There are... For example, this... https://github.com/GhostBasenji/blog-src and https://github.com/GhostBasenji/blog-src/blob/master/themes/notepadium/layouts/partials/note-list.html (or https://github.com/cntrump/hugo-notepadium)

Or as a solution, you can leave C# in the tags, and in the address bar like this: /tag/c.

**Comment by lxndrblz** [comment]
@GhostBasenji Thanks I will check how they circumvent the issue.

**Comment by lxndrblz** [comment]
It appears as they simply replace the problematic characters:

https://github.com/cntrump/hugo-notepadium/blob/37a4b7215f4fb563035eb9c1b8f661defc7b9954/layouts/partials/note-labels.html

```html
  {{- range .Params.tags -}}
      {{- $tag := replace . "#" "%23" -}}
      {{- $tag = replace $tag "." "%2e" -}}
      {{- $url := print "/tags/" ($tag | urlize) "/" -}}
      <a class="tag" href="{{- $url | relLangURL -}}">{{- . -}}</a>
  {{- end -}}
```
