### ISSUE TITLE
[params] author is actually the sites html title

### ISSUE THREAD

**Issue by brinkabeler** [lxndrblz/anatole#184]
**Describe the bug**
I expected "title" to be the config field for the site title and noticed that actually, the "author" field is used for the html website title.

**To Reproduce**
1. Put sting A in [params] author field in config.yaml
2. Put sting B in title field in config.yaml
3. Build site
4. Find string A in the <title>-tag of the finished website

**Expected behavior**
I expect the "title" parameter from the config.toml to be used for the html <title> attribute.

**Comment by lxndrblz** [comment]
@brinkabeler The behaviour you see is controlled via this piece of code:
https://github.com/lxndrblz/anatole/blob/2f0ff4dace953e870d2d2fbf1f9bd0d4da6a5651/layouts/partials/head.html#L2

As this site is intended for a single-author/personal site, the author's name gets pulled from the config, while the title gets pulled from the site/blog post. That is the case, because else all of your site would have the static title "author - title". In summary, there is no way to globally define the title, as it is controlled via the markdown headers.

**Comment by brinkabeler** [comment]
Thank you for the explanation! Maybe in that case it would make sense to remove the title parameter from the config file in the example site in order to avoid confusion.

I don‘t exactly mind the way this works, from the example config I just expected it to work differently. Now I know how it is intended I can work with it.

Thanks again!

**Comment by lxndrblz** [comment]
@brinkabeler Thanks for your feedback. Let me give you a bit more content, about the parameter in question. The title parameter you were tweaking doesn't adjust the html title, but the sidebar title. See this piece of code:

https://github.com/lxndrblz/anatole/blob/2f0ff4dace953e870d2d2fbf1f9bd0d4da6a5651/layouts/partials/sidebar.html#L5

Do you think the current documentation is not clear enough?

**Comment by brinkabeler** [comment]
I was referring to the title parameter above the [params] section. The one you refer to I understood fine.

**Comment by lxndrblz** [comment]
Oh gotcha. You mean this one right?

https://github.com/lxndrblz/anatole/blob/4beb92098a0c1565aca7e674c884992ee3723aad/exampleSite/config/_default/config.toml#L4

It is actually one of the default Hugo parameters. It is used through out various places, such as the rss feed.

**Comment by brinkabeler** [comment]
Exactly. Since this is not quite self-explanatory, I think some comments in the config file for the lines in question would be helpful.
