### ISSUE TITLE
Having the option to move to the right part of the main nav menu options

### ISSUE THREAD

**Issue by franferri** [lxndrblz/anatole#236]
In the menus.en.toml we have

`
  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  ...
`

Adding a parameter to say:
`
  align = "Right" -> so it moves the option to the part were the icon about dark/day is, just near to it.
`

**Comment by lxndrblz** [comment]
Thanks for your question. In this case, I would like to encourage you to use a custom CSS to get the desired effect. You could do something like this:

```css
nav__list {
    justify-content: flex-end;
}
...
```
It looks a bit cramped though. You may want to consider adding a bit of space before the theme switcher, if it is active on your site.

The reason, why I am not adding this directly is because I think it does not seem logical. Especially on larger screens the menu would drift off to the right side.

Hope that helps.
