### ISSUE TITLE
Option to display only content when clicking on a post.

### ISSUE THREAD

**Issue by jakevossen5** [lxndrblz/anatole#256]
**Is your feature request related to a problem? Please describe.**

When reading a post on my site, I feel like it is a little obnoxious to have my portrait, socials, etc taking up a lot of the screen

**Describe the solution you'd like**

An option in `config.toml` that allows you to hide the left pane while looking at a post

**Describe alternatives you've considered**

I could just make the left pane smaller overall, so it doesn't take up as much space on the homepage or the posts page

**Additional context**

**Comment by lxndrblz** [comment]
@jakevossen5 Thanks for your comment. This topic has been requested quite often and is already on my todo list (See this [issue](https://github.com/lxndrblz/anatole/projects/1#card-42912119)).

Unfortunately, it is still  an open issue, as theme heavily relies on having the sidebar and major changes have to be implemented. Otherwise the menu and content appear in a weirdly squashed manner. I will close this for now as it is already tracked on the project board.

**Comment by jakevossen5** [comment]
Ah makes sense - thank you!

**Comment by ThanhPhanTiki** [comment]
that annoying when view the post but still see the sidebar(avatar, shortlink stuffs...)
