### ISSUE TITLE
category links are not working correctly with slugs

### ISSUE THREAD

**Issue by slav123** [lxndrblz/anatole#257]
If you are using custom permalink to category:

`config.toml`

```
[permalinks]
categories = "/category/:slug/"
```

Links under the post aren't working correctly. They are still linking to `,categories/`

**Comment by lxndrblz** [comment]
@slav123 Thanks for reporting it. I will have to look into it as I hadn't encountered that before

**Comment by lxndrblz** [comment]
@slav123 Thanks for your question.

If you want to use a custom permalink for the taxonomies you would have to modify the `categories.html` inside of layouts/partials/taxonomy as following:
```html
{{ partial "taxonomy/template.html" (dict "items" . "linkClass" "category" "linkBase" "category") }}
```

Note that last parameter that has changed from "categories" to "category". The reason why this works, is because the `template.html` will then take this option and construct a valid URL from it. To the best of my knowledge, there is no automated way of retrieving this parameter from within the script.

I hope that helps.
