### ISSUE TITLE
Footnote pointing to homepage

### ISSUE THREAD

**Issue by lxndrblz** [lxndrblz/anatole#26]
The link of the footnote in the markdown example is pointing to the homepage rather than to the corresponding site.

https://themes.gohugo.io//theme/anatole/post/markdown-syntax/

**Comment by geoffreywwang** [comment]
I had this issue as well. This is because of the backref tag in the header. I removed it and footnotes work fine now, but it also broke relative pathing (which I haven't fixed).

Fixing this bug will lead to a new one that makes footnote backrefs scroll to the footnotes but hide them behind the nav bar. The fix required some CSS hacks.

I'm sorry that I don't have the time to submit a PR but you can check out 418e527 and 79eef83 for the changes I made regarding footnotes and check my [blog](https://geowang.com/post/2020-05-27-the-history-of-my-personal-website/) if you want to see it in action.

**Comment by geoffreywwang** [comment]
For anyone looking, the scroll padding css tag used here doesn't work on Safari. You might need to the snippet below to your `style.css` file as a hack. (Unfortunately, it isn't super consistent either, but the best workaround I was able to find.)

```
.footnote-ref::before {
     content: "";
     display: block;
     margin-top: -90px;
     padding-top: 90px;
     position: absolute;
 }
```
