### ISSUE TITLE
Add Search Bar to Search through all blog posts.

### ISSUE THREAD

**Issue by An0nUD4Y** [lxndrblz/anatole#302]
Hey @lxndrblz , Thank you for awesome theme.
It would be great , if it's possible to add a search bar to search through all the blog posts , It will make it easy to quickly search for particular text/blog content, which will be very helpful if someone if using the blog as reference and wants to search a particular text/command/code in the blog posts.

Again,  Thank you for the theme and your work. ❤️

**Comment by lxndrblz** [comment]
@An0nUD4Y Thanks for your suggestion.

For my other Hugo site, I've been quite successfully using lunr.js. I think this might also be an option for this theme.

The reason I haven't prioritized a search functionality until now, is because I think it hasn't been essential for small (personal) sites. 

I have put your suggestion on the todo list. Feel free to send an PR, if you are going to implement this enhancement.

**Comment by eclecticpassions** [comment]
+1 for adding search functionality! Thanks for your work on it @lxndrblz.

**Comment by lxndrblz** [comment]
After careful consideration I have decided to mark this request as "wont fix" as the overhead caused does not allign with the initial idea of a small and minmalistic theme.
