### ISSUE TITLE
RSS item descriptions do not consider actual post descriptions

### ISSUE THREAD

**Issue by alexanderdavide** [lxndrblz/anatole#340]
**Describe the bug**
RSS considers content or summary as `<description></>` and ignores descriptions supplied in post front matters. Also, the content's or summary's HTML tags are added which make them hard to use anyway.

**To Reproduce**

1. Create a post with description supplied in front matter.
2. See item's description on the RSS feed given on https://domain.tld/index.xml

Alternatively, see https://anatole-demo.netlify.app/index.xml.

**Expected behavior**
Description in front matters should be considered as `<description></>` in RSS feed.

**Comment by lxndrblz** [comment]
Hi @alexanderdavide, what you are describing is caused by this line in the rss.xml:

[        <description>{{ .Summary | html }}</description>](https://github.com/lxndrblz/anatole/blob/d3057a5a8e49e1dcddd71914fffd6e6685ba6aac/layouts/_default/rss.xml#L38)

As you can see the rss.xml file expects a summary. Personally, I always set up both a description and a summary. Both variables are default page variables:

https://gohugo.io/content-management/front-matter/

**Comment by alexanderdavide** [comment]
> Hi @alexanderdavide, what you are describing is caused by this line in the rss.xml:
> 
> https://github.com/lxndrblz/anatole/blob/80312357ceee167aa9f224281363933a47e27994/layouts/_default/rss.xml#L35-L39
> 
> As you can see the rss.xml file expects a summary. Personally, I always set up both a description and a summary. Both variables are default page variables:
> 
> https://gohugo.io/content-management/front-matter/

That's fine but what I'm asking is why isn't the `description` front matter used as RSS `<description>` element? I am setting `description` explicitly, I want it to be the description in RSS too. The summary should merely be a fallback.

**Comment by lxndrblz** [comment]
I agree. As the description is also the default in the arch type, we should exchange the summary variable for the description.
