### ISSUE TITLE
I cannot see my SocialIcon on github.io

### ISSUE THREAD

**Issue by JacksonK9** [lxndrblz/anatole#356]
**Describe the bug**
Hello, I can see my SocialIcon on the localhost
But, when I upload to the github.io, I cannot see my SocialIcon

**To Reproduce**

This is my blog - https://github.com/JacksonK9/blog
Can you check my data?

**Screenshots**
this is my localhost
![image](https://user-images.githubusercontent.com/20558677/168466107-47eeeb47-09f5-47a5-9d92-bd10cc8c6871.png)

this is my github.io
![image](https://user-images.githubusercontent.com/20558677/168466129-d4b1f69d-6ef3-4b75-924a-081d9a142494.png)

**Desktop (please complete the following information):**
- Windows 11 OS
- Whale, Microsoft Edge Browser
- hugo v0.95.0-9F2E76AF windows/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio

**SmartPhone
- Iphone 12 Pro max

**Additional context**
I already check this issue https://github.com/lxndrblz/anatole/issues/31

**Comment by lxndrblz** [comment]
Hi there,

the reason why they do not appear correctly is because of an integrity error.

![image](https://user-images.githubusercontent.com/12200062/169645287-3575fcd4-d1ec-4c6d-8581-5cd6a7ba4555.png)

Which version of the theme are you currently using? 
Additionally, you could check out this issue:

https://github.com/lxndrblz/anatole/issues/114

Hope that helps.

**Comment by JacksonK9** [comment]
After check your comment, I updated to the lastest version.
And I checked the line endings.
It works!

Thank you
I love your theme 👍
