### ISSUE TITLE
Disable title capitalization

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#368]
**Is your feature request related to a problem? Please describe.**
In some languages using capitalization of titles looks awesome because they have strict rules and capitalization is not a style, but a meaning (e.g. capitalized words are nouns).

**Describe the solution you'd like**
Please don't use the "title" processor in the template file. Use CSS instead. That makes it much easier to change the capitalization as wanted:

```css
text-transform: capitalize
```

As a user of your theme I will now be able to override the CSS style to disable capitalization if I need to:

```css
text-transform: none
```

**Describe alternatives you've considered**
I can provide my own `single.html` file. But when I do it, I have to monitor your changes in your `single.html` and merge them with my modifications. I prefer to use the CSS solution instead.

**Additional context**

**Comment by lxndrblz** [comment]
@McPringle Would you mind opening a PR with the proposed change?

**Comment by McPringle** [comment]
Next week we are doing a [Hackergarten in Lucerne](https://www.meetup.com/hackergarten-luzern/events/286786888/) and I'll suggest this issue as a topic.

**Comment by ericswpark** [comment]
I just realized what @McPringle meant by the capitalization problem and once I noticed it I really wish we could turn it off, as it mangles some of my blog post titles.

@lxndrblz could we make it an option to disable title capitalization in single pages?

**Comment by McPringle** [comment]
Unfortunately, this issue was not picked up at the Hackergarten. But winter is coming with more evenings at home... ;-)

**Comment by ericswpark** [comment]
@lxndrblz @McPringle just drafted a rough commit that adds a configuration option for single page titles.

I was also thinking about having the config option change the archive (list) title capitalization as well since I'd like to turn that off too but I realized that one is in all caps, so it's more of a stylistic choice? So either:

a) change the configuration option name to `disableTitleStyling` and have it disable all title styling (dunno how that would work on scss files though) or
b) change this configuration option name to `disableSinglePageTitleCapitalization` and _create a separate, new PR_ for `disableArchiveTitleStyling` or something like that. (Maybe the config name is too long. Or not.)

**Comment by McPringle** [comment]
Fantastic! For me variant b) would be enough, but variant a) would be fine, too. :-)

**Comment by McPringle** [comment]
Thank you very much, the new config options work on my updated blog like a charm!
