### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by lszczygielek** [lxndrblz/anatole#40]
Theme looks great. Is there a chance to support multiple languages?

**Comment by lxndrblz** [comment]
Hello @lszczygielek ,

Thanks for your inquiry and praise.

Right now there is no support for multiple languages, but I can see there is a need for many users. That's why I have added into the project's roadmap. However, it's also a bit laborious in terms of implementation and testing.  If you want to help, then feel free to open a PR. Contributions are always welcome!
