### ISSUE TITLE
Can we change the display content of the right column on the home page?

### ISSUE THREAD

**Issue by dingdl** [lxndrblz/anatole#50]
When I change "post" to "about" of the "mainSections" parameter, the right column of the home page will show nothing. What should I do to make the "About" show on the home page?

**Comment by lxndrblz** [comment]
@dingdl If I understood you correctly then you are trying to display your about page on the frontpage, where usually the posts are displayed. Unfortunately, such a scenario is not possible, as the index page is set up to display content of type posts and not single pages. Therefore, it's best to link your about page in the menu and put any content in the post folder.

In case you want to use the about folder instead of post then you could adjust it in the config.toml.

Hope that helps.
