### ISSUE TITLE
Theme is not rendered on Netlify

### ISSUE THREAD

**Issue by Rindrics** [lxndrblz/anatole#51]
Thank you for providing excellent theme!!

The theme works on localhost, but not on Netlify.
I investigated the page source and found that css is not loaded on my website.

I was following #48, but my case seems different from that.

Would you please how to fix my problem?

## on localhost
<img width="932" alt="image" src="https://user-images.githubusercontent.com/14845847/89463330-ba1b0800-d7a9-11ea-9fed-cf462259d598.png">

## on Netlify
<img width="948" alt="image" src="https://user-images.githubusercontent.com/14845847/89463409-d7e86d00-d7a9-11ea-9194-9133fb19abd4.png">

Thank you.

**Comment by lxndrblz** [comment]
@Rindrics  Thanks for your praise and for providing some valuable screenshots.

The problem here seems related to a CORS issue on your particular setup:

![image](https://user-images.githubusercontent.com/12200062/89489594-277b6880-d7ab-11ea-923a-8f770e0b8062.png)

Basically, the response to the CORS request is missing the required Access-Control-Allow-Origin header.

Could you please check if your domain (within Netlify's domain management) `www.rindrics.com`' is currently the primary and if `rendrics.com` is redirecting to it?

Did you clone the theme or add it as a submodule?

**Comment by Rindrics** [comment]
@lxndrblz I realized that you visited my website to investigate the problem.
Finally I managed to make my website be rendered.
Not the theme, but my domain setting caused the problem. I'm sorry.

Thank you for your support!
